import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import { Footer } from "./components/Footer";

export const metadata: Metadata = {
  title: "Next.js App Router Examples",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen justify-between">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
